language: generic 
sudo: required
services:
    - docker
before_install:
    # can do further builds here for tests
    - docker build -t 7664890/react-test -f ./client/Dockerfile.dev ./client
script:
     # can run further tests here
    - docker run -e CI=true USERNAME/react-test npm test
after_success:
    - docker build -t 7664890/multi-client ./client
    - docker build -t 7664890/multi-nginx ./nginx
    - docker build -t 7664890/multi-server ./server
    - docker build -t 7664890/multi-worker ./worker

# Log in to docker
- echo "$dP" | docker login -u "$dID" --password-stdin    
# Take those images and then push them to docker hub
- docker push 7664890/multi-client
- docker push 7664890/multi-nginx
- docker push 7664890/multi-server
- docker push 7664890/multi-worker